name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1

    - name: Compile
      run: ./mill -i __.compile

  publish:
    needs: compile
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1

      - name: Release
        run: ./mill -i mill.scalalib.PublishModule/publishAll --sonatypeCreds $SONATYPE_USERNAME:$SONATYPE_PASSWORD --gpgArgs --passphrase=$PGP_PASSPHRASE
        env:
          PGP_SECRET: ${{ secrets.PUBLISH_SECRET_KEY }}
          PGP_PASSPHRASE: ${{ secrets.PUBLISH_SECRET_KEY_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.PUBLISH_USER }}
          SONATYPE_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
